module.exports = {
    ROLE_TEST: 'ROLE_TEST',
    COMMAND_TEST_SAY_HELLO: 'SAY_HELLO',

    //ACCOUNT
    ROLE_ACCOUNT: 'ROLE_ACCOUNT',
    CMD_ACCOUNT_LOGIN: 'CMD_ACCOUNT_LOGIN',
    CMD_ACCOUNT_LOGIN_FB: 'CMD_ACCOUNT_LOGIN_FB',
    CMD_ACCOUNT_LOGIN_GG: 'CMD_ACCOUNT_LOGIN_GG',
    CMD_ACCOUNT_CREATE: 'CMD_ACCOUNT_CREATE',
    CMD_ACCOUNT_GET: 'CMD_ACCOUNT_GET',
    CMD_ACCOUNT_SEARCH: 'CMD_ACCOUNT_SEARCH',
    CMD_ACCOUNT_UPDATE_FIELD: 'CMD_ACCOUNT_UPDATE_FIELD',
    CMD_ACCOUNT_UPDATE: 'CMD_ADMIN_UPDATE',
    CMD_GET_USER_INFO_BY_TOKEN: 'CMD_GET_USER_INFO_BY_TOKEN',
    CMD_ACCOUNT_VALID_USERNAME: 'CMD_ACCOUNT_VALID_USERNAME',
    // ACCOUNT WEB
    CMD_CREATE_WEB_USER_ACCOUNT: 'CMD_CREATE_WEB_USER_ACCOUNT',
    CMD_WEB_ACCOUNT_UPDATE: 'CMD_WEB_ACCOUNT_UPDATE',
    CMD_RESET_PASSWORD: 'CMD_RESET_PASSWORD',
    CMD_RESEND_OTP_RESET_PASSWORD: 'CMD_RESEND_OTP_RESET_PASSWORD',
    CMD_VERIFY_OTP_RESET_PASSWORD: 'CMD_VERIFY_OTP_RESET_PASSWORD',
    CMD_GET_COURSE_ACTIVE: 'CMD_GET_COURSE_ACTIVE',

    ROLE_IO: 'ROLE_IO',
    CMD_IO_NEW_UPDATE_PRICE: 'CMD_IO_NEW_UPDATE_PRICE',
}
